[package]
authors = ["Interlay <contact@interlay.io>"]
edition = "2018"
name = "runtime"
version = "1.1.0"

[features]
default = []
parachain-metadata-kintsugi = []
parachain-metadata-testnet = []
standalone-metadata = []
testing-utils = [
  # "substrate-subxt/client",
  # "substrate-subxt-client",
  "tempdir",
  "interbtc",
  "rand",
]

[dependencies]
async-trait = "0.1.40"
backoff = {version = "0.3.0", features = ["tokio"]}
cfg-if = "1.0"
clap = "3.1"
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive", "full"]}
futures = "0.3.5"
log = "0.4.0"
serde = {version = "1.0.136", features = ["derive"]}
serde_json = "1.0.71"
thiserror = "1.0"
tokio = {version = "1.0", features = ["full"]}
url = "2"

# Substrate dependencies
frame-support = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17"}
sp-arithmetic = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17"}
sp-keyring = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17"}
sp-runtime = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17"}
sp-std = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17"}
sp-version = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17"}

# Subxt dependencies
# https://github.com/interlay/subxt/tree/polkadot-v0.9.17
subxt = {package = "subxt", git = "https://github.com/interlay/subxt", rev = "1193d94206a669c59cc5dd89486fecfa82ca584a"}
subxt-client = {package = "subxt-client", git = "https://github.com/interlay/subxt", rev = "1193d94206a669c59cc5dd89486fecfa82ca584a"}

jsonrpsee = {version = "0.8.0", features = ["macros", "jsonrpsee-types", "client", "jsonrpsee-ws-client", "jsonrpsee-client-transport"]}

# Polkadot dependencies
polkadot-parachain = {git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.17"}
xcm = {git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.17"}

# Dependencies for the testing utils for integration tests
interbtc = {package = "interbtc-standalone", git = "https://github.com/interlay/interbtc", rev = "22b7490625b34de6b04f5750eda5966083d98567", optional = true}
rand = {version = "0.7", optional = true}
tempdir = {version = "0.3.7", optional = true}
testchain = {package = "node-template", path = "../../testchain/node"}

# Substrate Stellar Dependencies
substrate-stellar-sdk = {git = "https://github.com/pendulum-chain/substrate-stellar-sdk", branch = "polkadot-v0.9.16"}

[dependencies.primitives]
git = "https://github.com/interlay/interbtc"
package = "interbtc-primitives"
rev = "22b7490625b34de6b04f5750eda5966083d98567"

[dependencies.module-bitcoin]
git = "https://github.com/interlay/interbtc"
package = "bitcoin"
rev = "22b7490625b34de6b04f5750eda5966083d98567"

[dependencies.module-btc-relay]
git = "https://github.com/interlay/interbtc"
package = "btc-relay"
rev = "22b7490625b34de6b04f5750eda5966083d98567"

[dependencies.module-oracle-rpc-runtime-api]
git = "https://github.com/interlay/interbtc"
package = "module-oracle-rpc-runtime-api"
rev = "22b7490625b34de6b04f5750eda5966083d98567"

[dev-dependencies]
env_logger = "0.8.3"
runtime = {path = ".", features = ["testing-utils"]}
tempdir = "0.3.7"
